# =============================================
# Build config
# =============================================

base:             .
root:             ..
src:              <%= site.base %>/application
dest:             <%= site.root %>/www

timestamp:        <%= new Date().getTime() %>

# Templates
templates:        <%= site.src %>/templates

# EXPRESS API
apiurl:           http://express-mariortdev.rhcloud.com/api